### ISSUE TITLE
Installation failed: 'bower' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by idocs8** [ohpyupi/glyphicons-only-bootstrap#1]
I try to install using following cmd:
"bower install glyphicons-only-bootstrap" at command line on Windows 7 and get the error message.  Did I do something wrong here?

**Comment by ohpyupi** [comment]
Can you share the error messages with us?

**Comment by ohpyupi** [comment]
If bower doesn't work, you can also try npm.
```
npm install glyphicons-only-bootstrap
```

Will close this issue in a week unless any replies are posted.

**Comment by ohpyupi** [comment]
Will close this issue.
